services:
  server:
    hostname: server
    image: node
    volumes:
      - ./:/opt/server
    ports:
      - "9000:9000"
      - "9001:9001"
    working_dir: /opt/server
    entrypoint: ["./docker-entrypoint.sh"]

  ngrok:
    hostname: ngrok
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --url=${NGROK_DOMAIN} server:9000
