services:
  server:
    hostname: server
    build:
      context: .
    volumes:
      - ./:/opt/server
    ports:
      - "9000:9000"
      - "9001:9001"
    working_dir: /opt/server

  ngrok:
    hostname: ngrok
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http server:9000
